### ISSUE TITLE
Execution failing in the tutorial whenever a REST service is needed

### ISSUE THREAD

**Issue by rafaelcn** [jpos/jPOS-template#18]
In tutorial 3, we set out to do a REST interface. Attending all the prerequisites specified in the tutorial (that is, the build files looks exactly as the tutorial wrote), when testing the Echo call the service fails.

Going through the initialization logger this message can be seen:

```
<log realm="slf4j::org.eclipse.jetty.webapp.StandardDescriptorProcessor" at="2020-08-11T15:15:12.765660">
  <info>
    NO JSP Support for /api, did not find org.apache.jasper.servlet.JspServlet
  </info>
</log>
```

The JSP service is unavailable and thus we cannot send an HTTP request to the server. I first thought this was a dependency error, but it isn't.  What could be happening in this case?

**Comment by barspi** [comment]
Thank you @rafaelcn 
We'll check and fix it.
Maybe the tutorial need to be updated

**Comment by rafaelcn** [comment]
Is it so? Let me know whenever you have it tested!

**Comment by ar** [comment]
That's just a Jetty info message, JSP is not used by the system.
